config/routes.rb
Rails.application.routes.draw do
  root "questions#index"
  resources :questions do
    resources :answers
  end
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question

  validates :description, length: { minimum: 50 }, presence: true
  validates :question_id, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ActiveRecord::Base
  has_many :answers, dependent: :destroy
  # validates :title, numericality: true, length: {minimum: 40}
  validates :title, length: { minimum: 40 }, presence: true
  # validates :description, numericality: true, length: {minimum: 150}
  validates :description, length: { minimum: 150 }, presence: true

end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

    def create
      @question = Question.find(params[:question_id])
      @answer = Answer.new(answer_params)
      @answer.question = @question

      if @answer.save
        flash[:notice] = "Answer saved successfully."
        redirect_to question_path(@question)
      else
        flash[:notice] = "Failed to save answer."
        redirect_to question_path(@question)
      end
    end

    def answer_params
      params.require(:answer).permit(:description)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  def index
    @questions = Question.order("created_at DESC").all
    @question = Question.new
    @answer = Answer.new
  end

  def show
    @question = Question.find(params[:id])
    @answers = @question.answers.order("created_at DESC")
    @answer = Answer.new
  end

  def edit
    @question = Question.find(params[:id])
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(question_params)
    if @question.save
      flash[:notice] = "You saved a question."
      redirect_to questions_path
    else
      flash[:notice] = "Did not save Question."
      render "new"
    end
  end

  def update
    @question = Question.find(params[:id])

    if @question.update(question_params)
      redirect_to questions_path
    else
      render :edit
    end
  end

  def destroy
    @question = Question.find(params[:id])
    @question.destroy
    redirect_to questions_path
  end

  private

  def question_params
    params.require(:question).permit(
      :title,
      :description
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RescueMission</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
    <%= yield %>
  </body>
</html>

app/views/questions/_answerform.html.erb
<%= form_for [@question, @answer] do |f| %>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %><br />
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/questions/_form.html.erb
<%= form_for(@question) do |f| %>

  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>
      <ul>
      <% @question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_area :title %>
  </div>

  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %><br />
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/questions/edit.html.erb
<%= render "form", question: @question %>
<%= link_to "Destroy", question_path(@question),
        method: :delete,
        data: { confirm: 'Are you sure?'}%>

app/views/questions/index.html.erb
<h1>Question Page</h1>

<body>

  <ul>
    <% @questions.each do |question| %>
      <li><%= link_to "#{question.title}", question %></li>
    <% end %>
  </ul>
  <%= render "form" %>

</body>

app/views/questions/new.html.erb
<%= render "form", question: @question %>

app/views/questions/show.html.erb
<h1> <%= @question.title %> </h1>
<body>
  <p> <%= @question.description %></p>
  <%= link_to "Edit", edit_question_path(@question) %>
  <%= link_to "Destroy", question_path(@question),
          method: :delete,
          data: { confirm: 'Are you sure?'}%>
  <%= render "answerform" %>
  <ul>
    <% @answers.each do |a|  %>
      <li><%= a.description %></li>
    <% end %>
  </ul>
</body>